-- Oracle DDL Reference (Assessment Brief Case A-002)

CREATE TABLE purchase_quote (
  id               NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  supplier_name    VARCHAR2(100) NOT NULL,
  item_code        VARCHAR2(50)  NOT NULL,
  quote_amount     NUMBER(14,2)  NOT NULL,
  quote_currency   VARCHAR2(3)   NOT NULL,   -- e.g. KRW, EUR, IDR
  base_currency    VARCHAR2(3)   DEFAULT 'USD',
  budget_amount    NUMBER(14,2)  NOT NULL,   -- in base currency
  converted_amount NUMBER(14,2),
  budget_flag      VARCHAR2(15),             -- WITHIN_BUDGET / OVER_BUDGET / UNKNOWN
  rate_used        NUMBER(18,6),             -- Rate used at time of calculation (P1 feature)
  rate_fetched_at  TIMESTAMP,                -- Timestamp when FX rate was fetched (P1 feature)
  created_at       TIMESTAMP     DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE fx_rate_cache (
  id               NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  base_currency    VARCHAR2(3)   NOT NULL,
  target_currency  VARCHAR2(3)   NOT NULL,
  rate             NUMBER(18,6)  NOT NULL,
  rate_date        DATE          NOT NULL,
  fetched_at       TIMESTAMP     DEFAULT CURRENT_TIMESTAMP
);
