-- ANSI SQL DDL compatible with PostgreSQL and H2

CREATE TABLE IF NOT EXISTS purchase_quote (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  supplier_name    VARCHAR(100) NOT NULL,
  item_code        VARCHAR(50)  NOT NULL,
  quote_amount     NUMERIC(14,2) NOT NULL,
  quote_currency   VARCHAR(3)   NOT NULL,
  base_currency    VARCHAR(3)   DEFAULT 'USD',
  budget_amount    NUMERIC(14,2) NOT NULL,
  converted_amount NUMERIC(14,2),
  budget_flag      VARCHAR(15),
  rate_used        NUMERIC(18,6),
  rate_fetched_at  TIMESTAMP,
  created_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS fx_rate_cache (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  base_currency    VARCHAR(3)   NOT NULL,
  target_currency  VARCHAR(3)   NOT NULL,
  rate             NUMERIC(18,6) NOT NULL,
  rate_date        DATE         NOT NULL,
  fetched_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_fx_cache_lookup ON fx_rate_cache(base_currency, target_currency, rate_date);
